CREATE TABLE IF NOT EXISTS shopping_list (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name TEXT NOT NULL,
    price decimal(10, 2) NOT NULL,
    date_added TIMESTAMP DEFAULT now() NOT NULL,
    checked BOOLEAN DEFAULT false NOT NULL,
    category grocery NOT NULL

);

SELECT name, price, date_added, checked, category
    FROM shopping_list
        WHERE date_added > (now() - '30 days':: INTERVAL)
    

-- SELECT name, price, date_added, checked, category
--     FROM shopping_list
--         WHERE date_added > (now() - '30 days':: INTERVAL)
--     GROUP BY price, name


-- SELECT name, price, date_added, checked, category
--     FROM shopping_list
--   LIMIT 6
--     OFFSET 50; 

-- SELECT name, price, date_added, checked, category
-- FROM shopping_list
--   WHERE name IS NOT NULL; 

DROP TYPE IF EXISTS category;
CREATE TYPE grocery AS ENUM (
    'Main',
    'Snack',
    'Lunch',
    'Breakfast'
);

